import { PrismaClient, User } from '@prisma/client';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { prisma } from '../server'; // Shared Prisma client

const JWT_SECRET = process.env.JWT_SECRET || 'your-very-secure-and-long-jwt-secret'; // Fallback for testing, ensure it's in .env for production

if (JWT_SECRET === 'your-very-secure-and-long-jwt-secret' && process.env.NODE_ENV === 'production') {
  console.warn('WARNING: JWT_SECRET is using a default insecure value in a production-like environment. Please set a strong secret in .env.');
}

export async function register(email: string, passwordInput: string, companyName: string): Promise<Omit<User, 'password'>> {
  // Check if user already exists
  const existingUser = await prisma.user.findUnique({ where: { email } });
  if (existingUser) {
    throw new Error('User with this email already exists.');
  }

  // Hash password
  const hashedPassword = await bcrypt.hash(passwordInput, 10);

  // Create company (or find, for now new company per registration is simpler as per instructions)
  // For production, you'd likely want to check if a company with this name exists and handle accordingly.
  let company = await prisma.company.findUnique({ where: { name: companyName } });
  if (!company) {
      company = await prisma.company.create({
          data: {
              name: companyName,
              // apiKey is auto-generated by Prisma's @default(uuid())
          },
      });
  }


  // Create user
  const user = await prisma.user.create({
    data: {
      email,
      password: hashedPassword,
      companyId: company.id,
      role: companyName === 'SentinelleAdmin' ? 'ADMIN' : 'COMPANY_ADMIN', // Example role logic
    },
  });

  const { password, ...userWithoutPassword } = user;
  return userWithoutPassword;
}

import { recordAuditEvent, AUDIT_ACTIONS } from './auditService'; // Added import

export async function login(email: string, passwordInput: string): Promise<{ token: string; user: Omit<User, 'password'> }> {
  const user = await prisma.user.findUnique({
    where: { email },
    include: { company: true }, // Include company info
  });

  if (!user) {
    throw new Error('Invalid email or password.');
  }

  const isPasswordValid = await bcrypt.compare(passwordInput, user.password);
  if (!isPasswordValid) {
    throw new Error('Invalid email or password.');
  }

  const token = jwt.sign(
    {
      userId: user.id,
      companyId: user.companyId,
      role: user.role,
      email: user.email, 
      companyName: user.company.name,
    },
    JWT_SECRET,
    { expiresIn: '1h' } 
  );

  // Record audit event for successful login
  await recordAuditEvent({
    action: AUDIT_ACTIONS.USER_LOGIN,
    userId: user.id,
    companyId: user.companyId,
  });

  const { password, ...userWithoutPassword } = user;
  return { token, user: userWithoutPassword };
}
